baseURL = "https://pavel.prischepa.me"
languageCode = "en-us"
title = "Pavel Prischepa"
theme = "anubis"
paginate = 3
googleAnalytics = "UA-23656190-3"
enableRobotsTXT = true
disqusShortname = "https-pavel-prischepa-me"

[author]
  name = "Pavel Prischepa"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
